### PR TITLE
Create Documentation Page “testing-out-netlify”

### PR DESCRIPTION
**Pull request by ryanhofdotgov**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
Hmm... this was not the desired effect. :) New repo (18F/move-marines) from Gatsby template, deployed to federalist, added `/admin` to URL to try out Netlify. Looks like Netlify added the PR here, instead of the new one.

**Comment by eddietejeda** [comment]
Ha! @davemcorwin you warned about this.

**Comment by davemcorwin** [comment]
@ryanhofdotgov yep, we're working on it, checkout our docs for instructions.

https://federalist.18f.gov/documentation/getting-started-with-netlify-cms/

**Comment by ryanhofdotgov** [comment]
Thanks @davemcorwin! I was able to figure it out shortly after this initial snafu – just grepped for `federalist-uswds-gatsby` in the repo files to find the line in `admin/config.yml`.

I wasn't even planning to give Netlify a spin at the time, but after a clone of the template repo and starting it locally, I think something was printed to the screen to go try out `/admin`.

Off-topic, but I'm impressed with how easy it was to get an initial PWA up and running with this template – just uncommented one line in the config. I think this is going to really help with: "we need an app..."

**Pull request closed without merging**
